package-lock.json
package.json
services/core/package-lock.json
services/core/package.json
services/gateway/package-lock.json
services/gateway/package.json
services/template/package-lock.json
services/template/package.json

This PR resolves #113
_- [] Deploy on public betanet node_ -> not possible due to the recent SDK update -> will be solved in #33 
n.a.

Production deployment - Closes #113

---

package-lock.json
package.json
services/core/package-lock.json
services/core/package.json
services/gateway/package-lock.json
services/gateway/package.json
services/template/package-lock.json
services/template/package.json

Version bump to 0.1.1 - Closes #147

---

framework/src/mapper.js
services/gateway/package-lock.json
services/gateway/package.json
services/gateway/shared/customMapper.js
services/gateway/shared/registerHttpApi.js
services/gateway/shared/registerRpcApi.js
tests/integration_testnet/api/http/accounts.test.js
tests/integration_testnet/api/http/compat.test.js
tests/integration_testnet/api/http/peers.test.js
tests/integration_testnet/api/rpc/accounts.test.js

Data transformer empty object not removed - Closes #143

---

services/core/shared/core/compat/sdk_v2/transactions.js
services/core/shared/core/transactions.js

Migrate transactions to blockchain data storage - Closes #137

---

services/core/methods/controllers/accounts.js
services/core/shared/core/accounts.js
services/core/shared/core/compat/sdk_v2/accounts.js
services/core/shared/core/compat/sdk_v2/index.js
services/core/shared/core/compat/sdk_v4/accounts.js
services/core/shared/core/compat/sdk_v4/index.js
services/gateway/sources/mappings/account.js
services/gateway/sources/mappings/transaction.js
tests/integration_testnet/api/http/delegates.test.js

This PR resolves #142 
Locally

Implement SDKv4 multisignature api - Closes #142

---

package-lock.json
package.json
services/core/package-lock.json
services/core/package.json
services/gateway/package-lock.json
services/gateway/package.json
services/template/package-lock.json
services/template/package.json

Version bump to 0.2.0-alpha.1 - Closes #206

---

services/core/shared/core/blocks.js
services/core/shared/core/dynamicFees.js
tests/integration/api/http/networkSearch.test.js
tests/integration/api/rpc/networkSearch.test.js

Fix dynamic fees errors - Closes #211

---

Makefile

Add make audit command - Closes #215

---

package-lock.json
package.json
services/core/package-lock.json
services/core/package.json
services/gateway/package-lock.json
services/gateway/package.json
services/template/package-lock.json
services/template/package.json

Version bump to 0.2.0-beta.0 - Closes #219

---

services/core/shared/core/transactions.js

Fix incorrect timestamp values returned for transactions

---

services/core/methods/controllers/accounts.js

Missing knowledge info - Closes #223

---

package-lock.json
package.json
services/core/package-lock.json
services/core/package.json
services/gateway/package-lock.json
services/gateway/package.json
services/template/package-lock.json
services/template/package.json

Version bump to 0.2.0-beta.1 - Closes #271

---

services/core/shared/core/compat/sdk_v2/transactions.js
services/core/shared/core/compat/sdk_v4/transactions.js
services/core/shared/core/transactions.js

Fixed transaction date conversion - Closes #274

---

services/core/shared/core/accounts.js
services/gateway/sources/mappings/account.js
tests/schemas/account.schema.js

Remove delegate properties for non-delegate account

---

services/core/Dockerfile

This PR resolves problems with deps and deps for sodium-native
Jenkins

Fix deps for sodium-native 

---

services/core/shared/core/compat/common/constants.js
services/core/shared/core/compat/common/index.js
services/core/shared/core/compat/sdk_v5/network.js
services/core/shared/core/compat/sdk_v5/transactions.js
services/core/shared/nodeStatus.js
services/gateway/apis/http-version2/methods/transactions.js
services/gateway/sources/version2/mappings/transaction.js
services/gateway/sources/version2/networkStatus.js
services/gateway/sources/version2/transactions.js

Rename operation to moduleAsset - Closes #304

---

services/core/shared/core/compat/sdk_v4/delegates.js

Fix totalVotesReceived - Closes #307

---

docs/api/websocket_subscribe_api.md
framework/bin/socket_io_subscribe_client.js
services/core/events/blockchain.js
services/core/shared/core/delegates.js
services/gateway/apis/socketio-blockchain-updates/config.js
services/gateway/apis/socketio-blockchain-updates/mappers/socketDelegate.js
services/gateway/app.js

This PR resolves #306
Local client

Fix forgers list - Closes #306

---

docker/Makefile.deployment
docker/Makefile.deployment.alphanet
docker/Makefile.deployment.betanet
docker/lisk_service/env/core.env
services/core/config.js
services/core/shared/core/blocks.js
services/core/shared/core/compat/sdk_v4/transactions.js
services/core/shared/core/events.js

This PR resolves #312 
Local IDE + Docker

Fix minor sorting issue - Closes #312

---

package-lock.json
package.json
services/core/package-lock.json
services/core/package.json
services/gateway/package-lock.json
services/gateway/package.json
services/template/package-lock.json
services/template/package.json

Version bump to 0.2.0-rc.0 - #310

---

docker/mysql/docker-compose.yml
services/core/jobs/knex_migration.js
services/core/shared/core/blocks.js
services/core/shared/core/compat/common/index.js
services/core/shared/core/compat/common/utils.js
services/core/shared/core/compat/sdk_v5/accounts.js
services/core/shared/core/compat/sdk_v5/blocks.js
services/core/shared/core/compat/sdk_v5/coreApi.js
services/core/shared/core/purge.js
services/core/shared/database/knex.js
services/core/shared/database/knex_migrations/blocks.js

This PR resolves #243 
- `blockId` as `id`
- `height`
- `timestamp`
- `generatorAddress`
- `generatorPublicKey` (To be indexed as a part of Accounts)
- `generatorUsername` (To be indexed as a part of Accounts)
- `height`
- `timestamp`
Local

Build block index - Closes #243

---

package-lock.json
package.json
services/core/package-lock.json
services/core/package.json
services/gateway/package-lock.json
services/gateway/package.json
services/template/package-lock.json
services/template/package.json

Tag 0.2.0-rc.1 - Closes  #334

---

services/core/methods/controllers/accounts.js
services/core/shared/core/accounts.js
services/core/shared/core/compat/sdk_v2/accounts.js
services/core/shared/core/compat/sdk_v2/index.js
services/core/shared/knownAccounts.js

Delegate properties - Closes #347

---

services/core/methods/controllers/transactions.js
services/core/shared/core/compat/sdk_v4/blocks.js
services/core/shared/core/compat/sdk_v4/transactions.js
services/core/shared/core/compat/sdk_v5/blocks.js
services/core/shared/core/delegates.js
services/core/shared/indexdb/mysql.js

Migrate transaction index to job queue - Closes #346

---

services/core/methods/controllers/transactions.js
services/core/shared/core/compat/sdk_v4/transactions.js
services/core/shared/indexdb/mysql.js

Fix transaction endpoint - Closes #340

---

package-lock.json
package.json
services/core/package-lock.json
services/core/package.json
services/gateway/package-lock.json
services/gateway/package.json
services/template/package-lock.json
services/template/package.json

Release 0.2.0-rc.2 - Closes #358

---

package-lock.json
package.json
services/core/package-lock.json
services/core/package.json
services/gateway/package-lock.json
services/gateway/package.json
services/template/package-lock.json
services/template/package.json

Tag production 0.2.0 - Closes #366

---

services/core/app.js
services/core/methods/controllers/transactions.js
services/core/shared/core/compat/sdk_v2/index.js
services/core/shared/core/compat/sdk_v3/index.js
services/core/shared/core/compat/sdk_v4/blocks.js
services/core/shared/core/compat/sdk_v5/blocks.js
services/core/shared/core/compat/sdk_v5/transactions.js
services/core/shared/core/queue.js
services/core/shared/core/transactionStatistics.js
services/core/shared/indexdb/mysql.js
services/gateway/apis/http-version2/methods/transactionsStatisticsDay.js
services/gateway/apis/http-version2/methods/transactionsStatisticsMonth.js
services/gateway/shared/status.js
services/gateway/sources/version2/mappings/transactionsStatistics.js
services/gateway/sources/version2/transactionsStatisticsDay.js
services/gateway/sources/version2/transactionsStatisticsMonth.js
tests/integration/api_v2/http/transactionStatistics.test.js

Transaction statistics - Closes #258

---

docker/lisk_service/env/core-postgres.env
docs/api/websocket_json_rpc_api.md
docs/config_options.md
docs/prerequisites_development_debian.md
docs/prerequisites_development_macos.md
docs/prerequisites_development_ubuntu.md
package-lock.json
package.json
services/core/package-lock.json
services/core/package.json
services/core/shared/core/compat/sdk_v4/transactions.js
services/gateway/package-lock.json
services/gateway/package.json
services/template/package-lock.json
services/template/package.json

This PR resolves #369 
Locally

Merge changes from 0.2.0 - Closes #369 

---

package-lock.json
package.json
services/core/package-lock.json
services/core/package.json
services/gateway/package-lock.json
services/gateway/package.json
services/template/package-lock.json
services/template/package.json

Tag 0.3.0-alpha.0 - Closes #395

---

services/core/shared/core/compat/sdk_v5/blocks.js
services/gateway/sources/version2/blocks.js
tests/integration/api_v2/http/blocks.test.js
tests/integration/api_v2/rpc/blocks.test.js

Fix block by id - Closes #397

---

README.md
docs/api/version2.md

Documentation update - Closes #415

---

services/core/package-lock.json
services/core/package.json
services/core/shared/core/compat/sdk_v5/schema/transactions.js
services/core/shared/core/compat/sdk_v5/transactions.js
services/core/shared/core/transactionStatistics.js
services/core/shared/indexdb/mysql.js
services/core/shared/requestAll.js
services/gateway/sources/version2/mappings/account.js

Fix transaction statistics - Closes #433

---

package-lock.json
package.json
services/core/package-lock.json
services/core/package.json
services/gateway/package-lock.json
services/gateway/package.json
services/template/package-lock.json
services/template/package.json

This PR resolves #458
Tagged the next alpha.
- Jenkins

Version bump to 0.3.0-alpha.2 - Closes #458

---

Jenkinsfile
services/gateway/shared/customMapper.js
tests/schemas/api_v2/account.schema.js

Fix unknown public key in response - Closes #457

---

package-lock.json
package.json
services/core/package-lock.json
services/core/package.json
services/gateway/package-lock.json
services/gateway/package.json
services/template/package-lock.json
services/template/package.json

This PR resolves #490
Tagged the beta.
Jenkins + Manual

Version bump to 0.3.0-beta.0 - Closes #490

---

framework/bin/moleculer_client.js
framework/bin/moleculer_subscribe.js
framework/bin/socket_io_rpc_client.js
framework/bin/socket_io_rpc_multirequest.js
framework/bin/socket_io_subscribe_client.js
framework/package-lock.json
framework/package.json
services/core/package-lock.json
services/core/package.json
services/gateway/package-lock.json
services/gateway/package.json

Dependencies update - Closes #438

---

services/core/ready.js
services/core/shared/core/compat/sdk_v5/accounts.js
services/core/shared/core/delegates.js
services/core/shared/jsonTools.js
services/core/tests/unit/jsonTools.test.js
services/core/tests/unit/signals.test.js

Add unit tests for core service - Closes #444

---

services/core/methods/api_v2/controllers/accounts.js
services/core/methods/api_v2/controllers/blocks.js
services/core/methods/api_v2/controllers/transactions.js
services/core/ready.js
services/core/shared/core/accounts.js
services/core/shared/core/compat/sdk_v5/accounts.js
services/core/shared/core/compat/sdk_v5/blocks.js
services/core/shared/core/compat/sdk_v5/coreApi.js
services/core/shared/core/compat/sdk_v5/pendingTransactions.js
services/core/shared/core/compat/sdk_v5/transactions.js
services/core/shared/core/compat/sdk_v5/voters.js
services/core/shared/exceptions/InvalidParamsException.js
services/core/shared/exceptions/NotFoundException.js
services/core/shared/exceptions/ValidationException.js
services/core/shared/exceptions/index.js
services/gateway/shared/exceptions/ValidationException.js
services/gateway/shared/exceptions/index.js
services/gateway/shared/ready.js
services/gateway/shared/registerHttpApi.js
services/gateway/shared/registerRpcApi.js

Update response codes - Closes #504

---

package-lock.json
package.json
services/core/package-lock.json
services/core/package.json
services/gateway/package-lock.json
services/gateway/package.json
services/template/package-lock.json
services/template/package.json

This PR resolves #517
- Tagged rc
Jenkins

Tag 0.3.0-rc.0 - Closes #517

---

services/core/shared/core/compat/sdk_v5/accounts.js
services/core/shared/core/compat/sdk_v5/transactions.js

Fix account updates - Closes #522

---

services/core/shared/core/compat/sdk_v5/voters.js
tests/integration/api_v2/http/accounts.test.js
tests/integration/api_v2/http/blocks.test.js
tests/integration/api_v2/http/transactions.test.js
tests/integration/api_v2/http/votesReceived.test.js
tests/integration/api_v2/rpc/accounts.test.js
tests/integration/api_v2/rpc/blocks.test.js
tests/integration/api_v2/rpc/transactions.test.js
tests/integration/api_v2/rpc/votesReceived.test.js
tests/schemas/voter.schema.js

Fix received votes response - Closes #524

---

services/core/README.md
services/core/package.json
services/gateway/README.md
services/gateway/package.json
services/template/README.md

Update readme - Closes #529

---

package-lock.json
package.json
services/core/Dockerfile
services/core/package-lock.json
services/core/package.json
services/gateway/package-lock.json
services/gateway/package.json
services/template/package-lock.json
services/template/package.json

This PR resolves #528
n/a
Jenkins

Tag 0.3.0-rc.1 - Closes #528

---

package-lock.json
package.json
services/core/package-lock.json
services/core/package.json
services/gateway/package-lock.json
services/gateway/package.json
services/template/package-lock.json
services/template/package.json

This PR resolves #535
Tagged `0.3.0`
Jenkins

Release production 0.3.0 - Closes #535

---

Jenkinsfile
Makefile
package-lock.json
package.json
services/core/Dockerfile
services/core/package-lock.json
services/core/package.json
services/core/shared/core/transactionStatistics.js
services/gateway/README.md
services/gateway/package-lock.json
services/gateway/package.json
services/template/README.md
services/template/package-lock.json
services/template/package.json

Fix transaction statistics - Closes #538

---

services/template/methods/hello.js

Mitigate DeepScan issues - Closes #439

---

services/market/config.js

This PR resolves #555
- Renamed variable names
Jenkins

Update env vars - Closes #555

---

framework/bin/moleculer_client.js
framework/bin/moleculer_subscribe.js
framework/bin/socket_io_rpc_client.js
framework/bin/socket_io_rpc_multirequest.js
framework/bin/socket_io_subscribe_client.js
framework/src/http.js
scripts/create_transaction_v4/create_transaction.js
services/core/tests/unit/jsonTools.test.js
services/core/tests/unit/signals.test.js
services/gateway/apis/socketio-jsonrpc-version1/routing.js
services/gateway/shared/moleculer-io/errors.js
services/gateway/shared/moleculer-io/index.js
services/gateway/shared/moleculer-web/methods.js
services/market/tests/functional/market.prices.test.js
tests/app.js
tests/helpers/node.js
tests/integration/api_v1/http/accounts.test.js
tests/integration/api_v1/http/blocks.test.js
tests/integration/api_v1/http/votesReceived.test.js
tests/integration/api_v1/http/votesSent.test.js
tests/integration/api_v1/rpc/blockEvent.test.js
tests/integration/api_v1/rpc/blocks.test.js
tests/integration/api_v2/http/accounts.test.js
tests/integration/api_v2/http/blocks.test.js
tests/integration/api_v2/http/market.test.js
tests/integration/api_v2/http/votesReceived.test.js
tests/integration/api_v2/http/votesSent.test.js
tests/integration/api_v2/rpc/blocks.test.js
tests/setup.js

Enable linter for certain files - Closes #442

---

docs/api/websocket_subscribe_api.md
services/core/events/blockchain.js
services/core/shared/core/compat/sdk_v5/blocks.js
services/core/shared/core/compat/sdk_v5/transactions.js
services/core/shared/core/events.js
services/gateway/apis/socketio-blockchain-updates/mappers/socketDelegate.js
services/gateway/app.js
services/gateway/sources/meta.js

Subscribe API content updates - Closes #549

---

package-lock.json
package.json
services/core/package-lock.json
services/core/package.json
services/gateway/package-lock.json
services/gateway/package.json
services/template/package-lock.json
services/template/package.json

This PR resolves #569 
Jenkins

Version bump to 0.4.0-alpha.0 - Closes #569

---

package-lock.json
package.json
services/core/package-lock.json
services/core/package.json
services/gateway/package-lock.json
services/gateway/package.json
services/template/package-lock.json
services/template/package.json

This PR resolves #588
- Tagged beta
Jenkins

Version bump to 0.4.0-beta.0 - Closes #588

---

known_accounts/known_mainnet.json

This PR resolves #526 #527
Manually

Update mainnet address list - Closes #526

---

package-lock.json
package.json
services/core/package-lock.json
services/core/package.json
services/gateway/package-lock.json
services/gateway/package.json
services/template/package-lock.json
services/template/package.json

Tag 0.4.0-rc.0 - Closes #595

---

services/core/config.js
services/core/shared/core/compat/sdk_v5/blocks.js
services/core/shared/core/compat/sdk_v5/dynamicFees.js

Configurable genesis height - Closes #601

---

Makefile
services/gateway/apis/http-version1/methods/newsfeed.js
services/gateway/apis/http-version1/swagger/definitions/newsfeed.json
services/gateway/apis/http-version1/swagger/parameters/newsfeed.json
services/gateway/apis/http-version2/methods/market.js
services/gateway/apis/http-version2/methods/newsfeed.js
services/gateway/apis/http-version2/swagger/definitions/market.json
services/gateway/apis/http-version2/swagger/definitions/newsfeed.json
services/gateway/apis/http-version2/swagger/parameters/accounts.json
services/gateway/apis/http-version2/swagger/parameters/newsfeed.json
services/gateway/app.js
services/gateway/sources/version1/mappings/newsfeed.js
services/gateway/sources/version1/newsfeed.js
services/gateway/sources/version2/mappings/newsfeed.js
services/gateway/sources/version2/newsfeed.js
services/newsfeed/methods/controllers/newsfeed.js
tests/integration/api_v1/http/newsfeed.test.js
tests/integration/api_v1/rpc/newsfeed.test.js
tests/integration/api_v2/http/newsfeed.test.js
tests/integration/api_v2/rpc/newsfeed.test.js
tests/schemas/newsfeed.schema.js

Retrieve news/blog posts - Closes #579

---

docker/redis/redis.persistent.conf
services/core/shared/core/compat/sdk_v5/blocks.js

Update index readiness - Closes #601

---

Jenkinsfile
Makefile
services/market/package-lock.json
services/market/package.json
services/newsfeed/Dockerfile
services/newsfeed/jest.config.functional.js
services/newsfeed/methods/controllers/newsfeed.js
services/newsfeed/methods/newsfeed.js
services/newsfeed/package-lock.json
services/newsfeed/package.json
services/newsfeed/shared/newsfeed.js
services/newsfeed/tests/functional/newsfeed.test.js
services/newsfeed/tests/schemas/newsfeedArticle.schema.js
services/newsfeed/tests/schemas/serviceUnavailable.schema.js
tests/schemas/newsfeed.schema.js

Retrieve news - Closes #580

---

docker/redis/redis.persistent.conf
package-lock.json
package.json
services/core/config.js
services/core/package-lock.json
services/core/package.json
services/core/shared/core/compat/sdk_v5/blocks.js
services/core/shared/core/compat/sdk_v5/dynamicFees.js
services/gateway/package-lock.json
services/gateway/package.json
services/template/package-lock.json
services/template/package.json

In order to update the CD environment the 0.4.0 changes need to be merged into the development branch.
- Review recent changes
- Merge recent changes
Jenkins

Merge development 0.4.0

---

package-lock.json
package.json
services/core/package-lock.json
services/core/package.json
services/gateway/package-lock.json
services/gateway/package.json
services/template/package-lock.json
services/template/package.json

This PR resolves #606
Jenkins + smoke test

Publish 0.4.0-rc.1 - Closes #606

---

package-lock.json
package.json
services/core/package-lock.json
services/core/package.json
services/gateway/package-lock.json
services/gateway/package.json
services/template/package-lock.json
services/template/package.json

Version bump to 0.4.0 - Closes #614

---

services/newsfeed/config_twitter.js
services/newsfeed/jobs/twitter.js
services/newsfeed/shared/newsfeed.js
services/newsfeed/shared/normalizers.js
services/newsfeed/shared/twitter.js
services/newsfeed/tests/unit/normalizer.test.js
tests/integration/api_v2/http/newsfeed.test.js
tests/integration/api_v2/rpc/newsfeed.test.js

Add Twitter data source - Closes #581

---

framework/src/http.js

This PR resolves #214
- Add debug messages for HTTP layer 
Jenkins

Improve debug messages - Closes #214

---

services/core/events/blockchain.js
services/core/jobs/delegates.js
services/core/shared/core/compat/sdk_v5/accounts.js
services/core/shared/core/compat/sdk_v5/blocks.js
services/core/shared/core/delegates.js
services/core/shared/geolocation.js
services/core/shared/requestAll.js
services/gateway/apis/http-version2/methods/transactions.js
services/gateway/apis/http-version2/methods/transactionsSchemas.js
tests/integration/api_v2/http/transactions.test.js

Performance fixes - Closes #617

---

Jenkinsfile
Jenkinsfile.deployment
services/core/events/blockchain.js
services/core/jobs/missingBlocks.js
services/core/shared/core/accounts.js
services/core/shared/core/compat/sdk_v5/accounts.js
services/core/shared/core/compat/sdk_v5/pendingTransactions.js
services/core/shared/core/compat/sdk_v5/transactions.js
services/core/shared/core/events.js
services/gateway/app.js

Fix performance issues - Closes #617

---

Jenkinsfile
services/core/config.js
services/core/jobs/delegates.js
services/core/shared/core/compat/sdk_v5/accounts.js
services/core/shared/core/compat/sdk_v5/index.js
services/core/shared/core/delegates.js
services/core/shared/core/queue.js
services/core/shared/indexdb/mysql.js

Fix delegate rank calculation - Closes #638

---

package-lock.json
package.json
services/core/package-lock.json
services/core/package.json
services/gateway/package-lock.json
services/gateway/package.json
services/template/package-lock.json
services/template/package.json

This PR resolves #644
- Version set to 0.4.1
Jenkins

Version bump to 0.4.1 - Closes #644

---

services/core/shared/core/compat/sdk_v5/accounts.js
services/core/shared/core/compat/sdk_v5/schema/multisignature.js
services/core/shared/core/compat/sdk_v5/transactions.js
services/gateway/sources/version2/mappings/account.js

Fix multisignature memberships - Closes #600

---

package-lock.json
package.json
services/core/package-lock.json
services/core/package.json
services/gateway/package-lock.json
services/gateway/package.json
services/template/package-lock.json
services/template/package.json

This PR resolves #666
- Tagged version and pushed
- Triggered Docker build
Jenkins

Version bump to 0.4.2 - Closes #666

---

README.md
docs/config_options.md

Documentation update - Closes #699

---

ecosystem.core3.config.js

This PR resolves #703
- Updated ecosystem file
Jenkins

Update pm2 config - Closes #703

---

package-lock.json
package.json
services/core/package-lock.json
services/core/package.json
services/gateway/package-lock.json
services/gateway/package.json
services/template/package-lock.json
services/template/package.json

Version bump to 0.4.3 - Closes #705

---

ecosystem.core3.config.js
framework/test/functional/http.test.js
services/core/shared/core/compat/sdk_v5/accountUtils.js
services/core/shared/core/compat/sdk_v5/blocks.js

Fix heavy load on core - Closes #714

---

package-lock.json
package.json
services/core/package-lock.json
services/core/package.json
services/gateway/package-lock.json
services/gateway/package.json
services/template/package-lock.json
services/template/package.json

Version bump to 0.4.4 - Closes #716

---

services/core/shared/core/compat/sdk_v5/accounts.js

This PR resolves #735 
Local against the Testnet for account: `lskfsk56b28e5byfxmw8944oc3er6bsmq3jag3nw4`

Fix unlocking periods calculation - Closes #735

---

package-lock.json
package.json
services/core/package-lock.json
services/core/package.json
services/gateway/package-lock.json
services/gateway/package.json
services/market/package-lock.json
services/market/package.json
services/newsfeed/package-lock.json
services/newsfeed/package.json
services/template/package-lock.json
services/template/package.json

This PR resolves #587
- Version bump
Jenkins

Version bump to 0.5.0-alpha.0 - Closes #587

---

Makefile
package-lock.json
package.json
services/core/package-lock.json
services/core/package.json
services/gateway/package-lock.json
services/gateway/package.json
services/market/package-lock.json
services/market/package.json
services/template/package-lock.json
services/template/package.json

Release 0.4.5 - Closes #751

---

Makefile
services/core/shared/core/compat/sdk_v5/accountUtils.js
services/core/shared/core/compat/sdk_v5/accounts.js
services/core/shared/core/compat/sdk_v5/coreApi.js

This PR merges 0.4.5 with 0.5.0

Merge 0.4.5 with 0.5.0

---

docker/lisk-service/docker-compose.core.yml
docker/lisk-service/docker-compose.newsfeed.yml
services/core/shared/core/compat/sdk_v5/blocks.js

This PR resolves #773
Local + Jenkins + Linux

Update block index procedure - Closes #773

---

package-lock.json
package.json
services/core/package-lock.json
services/core/package.json
services/core/shared/core/delegates.js
services/gateway/package-lock.json
services/gateway/package.json
services/market/package-lock.json
services/market/package.json
services/newsfeed/package-lock.json
services/newsfeed/package.json
services/newsfeed/shared/twitter.js
services/template/package-lock.json
services/template/package.json

Release 0.5.0 - Closes #847

---

docker/example.env
docs/migration_guide.md
package-lock.json
package.json
services/core/Dockerfile
services/core/package-lock.json
services/core/package.json
services/export/Dockerfile
services/export/package-lock.json
services/export/package.json
services/gateway/package-lock.json
services/gateway/package.json
services/market/package-lock.json
services/market/package.json
services/newsfeed/package-lock.json
services/newsfeed/package.json
services/template/package-lock.json
services/template/package.json

This PR resolves #879
Linux host + Local

Release 0.6.0-alpha.0 - Closes #879

---

package-lock.json
package.json
services/core/package-lock.json
services/core/package.json
services/export/package-lock.json
services/export/package.json
services/gateway/package-lock.json
services/gateway/package.json
services/market/package-lock.json
services/market/package.json
services/newsfeed/package-lock.json
services/newsfeed/package.json
services/template/package-lock.json
services/template/package.json

Version bump to 0.6.0-beta.0 - Closes #890

---

services/gateway/apis/http-exports/methods/export.js
services/gateway/namespaces.js
tests/helpers/utils.js
tests/integration/api_v2/http/export.test.js
tests/integration/api_v2/rpc/export.test.js
tests/package-lock.json
tests/package.json
tests/schemas/api_v2/export.schema.js

Add integration test cases - Closes #887

---

services/core/shared/core/compat/sdk_v5/blocks.js
services/core/shared/core/compat/sdk_v5/paramUtils.js
services/core/shared/core/compat/sdk_v5/transactions.js
tests/integration/api_v2/http/transactions.test.js
tests/integration/api_v2/rpc/transactions.test.js

Fix height range for transaction endpoint - Closes #900

---

services/core/shared/core/compat/sdk_v5/pendingTransactions.js
tests/schemas/api_v2/newsfeed.schema.js

This PR resolves #909 
Locally against test blockchain

Update failing integration tests - Closes #909

---

.eslintignore
.gitignore
Makefile
docs/migration_guide.md

This PR resolves #906
Linux + Jenkins

Migration guide update - Closes #906

---

docker-compose.yml
jenkins/mariadb/Makefile
jenkins/mariadb/docker-compose.yml
services/export/Dockerfile

This PR resolves #916 
Local + Linux

Create data directory in Dockerfile - Closes #916

---

Jenkinsfile.deployment.mainnet
Jenkinsfile.performance.mainnet
Jenkinsfile.regression.mainnet

Create Jenkinsfile for weekly mainnet tests - Closes #845

---

docs/config_options.md
package-lock.json
package.json
services/core/package-lock.json
services/core/package.json
services/export/package-lock.json
services/export/package.json
services/gateway/package-lock.json
services/gateway/package.json
services/market/package-lock.json
services/market/package.json
services/newsfeed/package-lock.json
services/newsfeed/package.json
services/template/package-lock.json
services/template/package.json

Release version 0.6.0-rc.1 - Closes #928

---

docs/CODE_OF_CONDUCT.md
docs/CONTRIBUTING.md

This PR resolves #933
- Updated guidelines
- Click on email and check navigation and send test email

Update contributing guidelines - Closes #933

---

package-lock.json
package.json
services/core/package-lock.json
services/core/package.json
services/export/package-lock.json
services/export/package.json
services/gateway/package-lock.json
services/gateway/package.json
services/market/package-lock.json
services/market/package.json
services/newsfeed/package-lock.json
services/newsfeed/package.json
services/template/package-lock.json
services/template/package.json

This PR resolves #950
- Bump version

Tag release candidate (0.6.0) - Closes #950

---

services/core/shared/core/compat/sdk_v5/transactions.js
services/core/shared/indexdb/mysql.js
services/newsfeed/shared/indexdb/mysql.js

Account exports are missing incoming transactions - Closes #953

---

services/market/jobs/binance.js
services/market/jobs/bittrex.js
services/market/jobs/exchangeratesapi.js
services/market/jobs/kraken.js
services/market/shared/market/sources/binance.js
services/market/shared/market/sources/bittrex.js
services/market/shared/market/sources/kraken.js

This PR resolves #793 
Local + Docker

Fix binance import error - Closes #793

---

services/core/shared/core/delegates.js

This PR resolves #972
Local + Linux + Jenkins

Update minimum eligible vote weight - Closes #972

---

ecosystem.core3.config.js
jenkins/lisk-core/.gitignore
jenkins/lisk-core/entrypoint_local.sh
jenkins/mariadb/docker-compose.yml
package-lock.json
package.json
services/core/package-lock.json
services/core/package.json
services/export/package-lock.json
services/export/package.json
services/gateway/package-lock.json
services/gateway/package.json
services/market/package-lock.json
services/market/package.json
services/newsfeed/package-lock.json
services/newsfeed/package.json
services/template/package-lock.json
services/template/package.json
tests/regression/api_v2/testnet/expectedResponse/http/accounts.js
tests/regression/api_v2/testnet/expectedResponse/rpc/accounts.js

Release 0.6.1 - Closes #976

---

services/core/shared/core/compat/sdk_v5/paramUtils.js
services/core/tests/unit/paramUtils.test.js

Fix false error issue for range based queries - Closes #990

---

services/core/shared/core/compat/sdk_v5/blockchainIndex.js

Fix snapshot issues - Closes #978 

---

package-lock.json
package.json
services/core/package-lock.json
services/core/package.json
services/export/package-lock.json
services/export/package.json
services/gateway/package-lock.json
services/gateway/package.json
services/market/package-lock.json
services/market/package.json
services/newsfeed/package-lock.json
services/newsfeed/package.json
services/template/package-lock.json
services/template/package.json

Release 0.6.2 - Closes #1016

---

services/core/Dockerfile
services/export/Dockerfile
services/gateway/Dockerfile
services/market/Dockerfile
services/newsfeed/Dockerfile
services/template/Dockerfile
tests/Dockerfile

This PR resolves #1020 
Local (docker)

Update Dockerfile - Closes #1020

---

services/blockchain-indexer/methods/dataService/accounts.js
services/blockchain-indexer/methods/dataService/controllers/accounts.js
services/blockchain-indexer/shared/dataService/accounts.js
services/blockchain-indexer/shared/dataService/index.js
services/gateway/apis/http-version3/methods/legacyAccounts.js
services/gateway/shared/regex.js
services/gateway/sources/version3/legacyAccountsSchema.js
tests/integration/api_v3/http/legacyAccounts.test.js
tests/integration/api_v3/rpc/legacyAccounts.test.js
tests/schemas/api_v3/legacyAccountsSchema.schema.js
tests/schemas/api_v3/regex.js

Export legacy information - Closes #1099

---

services/core/shared/core/compat/sdk_v5/accounts.js
services/core/shared/core/compat/sdk_v5/blockchainIndex.js

This PR resolves #1170 
Against the mainnet

 Fix legacy cache handling - Closes #1170

---

Makefile
docker-compose.yml
ecosystem.config.js
jenkins/Jenkinsfile
jenkins/Jenkinsfile.nightly
services/blockchain-app-registry/.dockerignore
services/blockchain-app-registry/.editorconfig
services/blockchain-app-registry/.gitignore
services/blockchain-app-registry/Dockerfile
services/blockchain-app-registry/README.md
services/blockchain-app-registry/app.js
services/blockchain-app-registry/config.js
services/blockchain-app-registry/events/hello.js
services/blockchain-app-registry/jobs/job.js
services/blockchain-app-registry/methods/hello.js
services/blockchain-app-registry/methods/status.js
services/blockchain-app-registry/package-lock.json
services/blockchain-app-registry/package.json
services/blockchain-app-registry/shared/database/schema/applications.js
services/blockchain-app-registry/shared/database/schema/tokens.js

Create new microservice - Closes #1200

---

framework/package-lock.json
package-lock.json
services/blockchain-connector/package-lock.json
services/blockchain-connector/package.json
services/blockchain-connector/shared/sdk/decoder.js
services/blockchain-coordinator/package-lock.json
services/blockchain-indexer/package-lock.json
services/blockchain-indexer/package.json
services/blockchain-indexer/shared/dataService/business/blocks.js
services/blockchain-indexer/shared/dataService/network.js
services/blockchain-indexer/shared/indexer/votersIndex.js
services/blockchain-indexer/shared/knownAccounts.js
services/blockchain-indexer/shared/utils/accountUtils.js
services/blockchain-indexer/shared/utils/eventsUtils.js
services/export/package-lock.json
services/export/package.json
services/export/shared/helpers/account.js
services/fee-estimator/package-lock.json
services/fee-estimator/package.json
services/gateway/apis/http-status/methods/status.js
services/gateway/package-lock.json
services/gateway/shared/status.js
services/market/package-lock.json
services/newsfeed/package-lock.json
services/template/package-lock.json
services/transaction-statistics/package-lock.json
tests/package-lock.json
tests/schemas/status.schema.js

Fix breaking changes from Lisk SDK - Closes #1193

---

services/blockchain-connector/shared/sdk/client.js
services/blockchain-coordinator/app.js
services/blockchain-coordinator/jobs/missingBlocks.js
services/blockchain-coordinator/shared/scheduler.js
services/blockchain-coordinator/shared/sources/indexer.js
services/blockchain-indexer/methods/indexer/indexer.js
services/blockchain-indexer/shared/dataService/business/blocks.js
services/blockchain-indexer/shared/database/schema/blocks.js
services/blockchain-indexer/shared/indexer/blockchainIndex.js

Add job to index missing blocks - Closes #1190

---

services/blockchain-connector/shared/sdk/client.js
services/blockchain-connector/shared/sdk/genesisBlock.js
services/blockchain-coordinator/package-lock.json
services/blockchain-coordinator/package.json
services/blockchain-coordinator/shared/scheduler.js
services/blockchain-indexer/shared/constants.js
services/blockchain-indexer/shared/eventsProcessor.js
services/blockchain-indexer/shared/indexer/blockchainIndex.js

This PR resolves #1267 
- Local 
- Linux

Improve client implementation in connector service - Closes #1267

---

services/blockchain-connector/shared/sdk/decoder.js
services/blockchain-indexer/shared/indexer/blockchainIndex.js
tests/integration/api_v3/http/schemas.test.js
tests/integration/api_v3/rpc/schemas.test.js
tests/schemas/api_v3/allSchemas.schema.js
tests/schemas/api_v3/constants/schemas.js

Add tests for schemas endpoint - Closes #1286

---

services/blockchain-indexer/shared/constants.js
services/blockchain-indexer/shared/dataService/business/tokens.js
services/gateway/apis/http-version3/swagger/definitions/tokens.json
services/gateway/sources/version3/mappings/tokenSummary.js
services/gateway/sources/version3/tokensSummary.js
tests/schemas/api_v3/regex.js
tests/schemas/api_v3/tokensSummary.schema.js

Update response for supported tokens

---

services/blockchain-connector/package-lock.json
services/blockchain-connector/package.json
services/blockchain-indexer/package-lock.json
services/blockchain-indexer/package.json
services/export/package-lock.json
services/export/package.json
services/fee-estimator/package-lock.json
services/fee-estimator/package.json

Update lisk sdk to v6.0.0 alpha.6 - Closes #1307

---

services/blockchain-app-registry/methods/metadata.js
services/blockchain-app-registry/shared/metadata.js
services/gateway/apis/http-version3/methods/blockchainAppsMetadata.js
services/gateway/apis/http-version3/swagger/parameters/blockchainApps.json
services/gateway/shared/regex.js
services/gateway/sources/version3/blockchainAppsMetadataSchema.js
tests/integration/api_v3/http/blockchainAppsMetadata.test.js
tests/integration/api_v3/rpc/blockchainAppsMetadata.test.js

Extend off-chain metadata endpoint

---

framework/package-lock.json
package-lock.json
services/blockchain-app-registry/package-lock.json
services/blockchain-connector/package-lock.json
services/blockchain-connector/package.json
services/blockchain-coordinator/package-lock.json
services/blockchain-indexer/package-lock.json
services/blockchain-indexer/package.json
services/export/package-lock.json
services/fee-estimator/package-lock.json
services/fee-estimator/package.json
services/gateway/package-lock.json
services/market/package-lock.json
services/newsfeed/package-lock.json
services/template/package-lock.json
services/transaction-statistics/package-lock.json
tests/package-lock.json

This PR resolves #1321 
- Upgrade Lisk SDK dependencies to `v6.0.0-alpha.7` for all the microservices
- Start Lisk Service against Lisk Core `v4.0.0-alpha.5`

Update Lisk SDK to v6.0.0-alpha.7

---

services/blockchain-indexer/methods/dataService/controllers/dynamicReward.js
services/blockchain-indexer/methods/dataService/dynamicReward.js
services/blockchain-indexer/shared/dataService/business/dynamicReward/constants.js
services/blockchain-indexer/shared/dataService/business/dynamicReward/index.js
services/blockchain-indexer/shared/dataService/business/index.js
services/blockchain-indexer/shared/dataService/dynamicReward/index.js
services/blockchain-indexer/shared/dataService/dynamicReward/rewardConstants.js
services/blockchain-indexer/shared/dataService/index.js
services/blockchain-indexer/shared/utils/request.js
services/gateway/apis/http-version3/methods/rewardConstants.js
services/gateway/apis/http-version3/swagger/definitions/dynamicReward.json
services/gateway/apis/http-version3/swagger/parameters/common.json
services/gateway/apis/http-version3/swagger/parameters/dynamicReward.json
services/gateway/sources/version3/rewardConstants.js
tests/integration/api_v3/http/rewardConstants.test.js
tests/integration/api_v3/rpc/rewardConstants.test.js
tests/schemas/api_v3/rewardConstants.schema.js

Create Reward Constants endpoint

---

services/blockchain-connector/methods/pos.js
services/blockchain-connector/package-lock.json
services/blockchain-connector/package.json
services/blockchain-connector/shared/sdk/index.js
services/blockchain-connector/shared/sdk/pos.js
services/blockchain-indexer/package-lock.json
services/blockchain-indexer/package.json
services/blockchain-indexer/shared/dataService/business/pos/lockedRewards.js
services/export/package-lock.json
services/export/package.json
services/fee-estimator/package-lock.json
services/fee-estimator/package.json

Update Lisk SDK to v6.0.0-alpha.8

---

services/blockchain-connector/package-lock.json
services/blockchain-connector/package.json

Update Lisk SDK to v6.0.0-alpha.9

---

docker/redis.persistent.conf
services/core/shared/core/compat/sdk_v5/accounts.js
services/core/shared/core/compat/sdk_v5/blockchainIndex.js

Improper legacy cache handling

---

services/blockchain-connector/package-lock.json
services/blockchain-connector/package.json
services/blockchain-indexer/package-lock.json
services/blockchain-indexer/package.json
services/blockchain-indexer/shared/dataService/business/pendingTransactions.js
services/blockchain-indexer/shared/dataService/business/pos/validators.js
services/fee-estimator/package-lock.json
services/fee-estimator/package.json
services/gateway/sources/version3/mappings/posValidator.js

Update Lisk SDK to v6.0.0-alpha.12

---

services/blockchain-indexer/methods/dataService/modules/pos.js
services/blockchain-indexer/shared/dataService/business/pos/unlocks.js
services/gateway/apis/http-version3/methods/modules/pos/posUnlocks.js
services/gateway/apis/http-version3/swagger/apiJson.json
services/gateway/apis/http-version3/swagger/definitions/pos.json
services/gateway/apis/http-version3/swagger/parameters/pos.json
services/gateway/sources/version3/mappings/posUnlock.js
services/gateway/sources/version3/posUnlocks.js
tests/integration/api_v3/http/posUnlocks.test.js
tests/integration/api_v3/rpc/posUnlocks.test.js
tests/schemas/api_v3/unlock.schema.js

Update unlocks endpoint

---

framework/package-lock.json
package-lock.json
services/blockchain-app-registry/package-lock.json
services/blockchain-connector/package-lock.json
services/blockchain-connector/package.json
services/blockchain-connector/shared/sdk/constants/eventTopics.js
services/blockchain-connector/shared/sdk/constants/names.js
services/blockchain-connector/shared/sdk/schema.js
services/blockchain-coordinator/package-lock.json
services/blockchain-indexer/package-lock.json
services/blockchain-indexer/package.json
services/blockchain-indexer/shared/dataService/business/pos/validators.js
services/blockchain-indexer/shared/indexer/blockchainIndex.js
services/blockchain-indexer/shared/utils/request.js
services/export/package-lock.json
services/fee-estimator/package-lock.json
services/fee-estimator/package.json
services/gateway/package-lock.json
services/market/package-lock.json
services/newsfeed/package-lock.json
services/template/package-lock.json
services/transaction-statistics/package-lock.json
tests/package-lock.json

This PR resolves #1462
- Run Lisk Service against Lisk Core (branch: `711-update-lisk-sdk-to-v6-0-0-alpha-13` commit: [88dbdd1](https://github.com/LiskHQ/lisk-core/pull/716/commits/88dbdd1a581155fd16f15ebf27adf367af834a25))
- Post transactions against Lisk Core with `npm run test:stress`

Update Lisk SDK to v6.0.0-alpha.13

---

services/blockchain-connector/methods/auth.js
services/blockchain-connector/shared/sdk/auth.js
services/blockchain-connector/shared/sdk/index.js
services/blockchain-indexer/shared/constants.js
services/blockchain-indexer/shared/dataService/business/auth/index.js
services/blockchain-indexer/shared/dataService/business/auth/multiSigRegMsgSchema.js
services/blockchain-indexer/shared/dataService/business/schemas.js
services/gateway/apis/http-version3/methods/schemas.js
services/gateway/apis/http-version3/swagger/definitions/schemas.json
services/gateway/sources/version3/mappings/schema.js
tests/integration/api_v3/http/schemas.test.js
tests/integration/api_v3/rpc/schemas.test.js
tests/schemas/api_v3/allSchemas.schema.js
tests/schemas/api_v3/constants/schemas.js

This PR resolves #1449 
- Response matches as shown below
-  [x] Local

Extend schemas endpoint

---

framework/package-lock.json
package-lock.json
services/blockchain-app-registry/package-lock.json
services/blockchain-connector/app.js
services/blockchain-connector/package-lock.json
services/blockchain-connector/package.json
services/blockchain-connector/shared/sdk/dynamicReward.js
services/blockchain-connector/shared/sdk/fee.js
services/blockchain-coordinator/package-lock.json
services/blockchain-indexer/package-lock.json
services/export/package-lock.json
services/fee-estimator/package-lock.json
services/fee-estimator/shared/dynamicFees.js
services/gateway/apis/http-version3/swagger/definitions/fees.json
services/gateway/package-lock.json
services/market/package-lock.json
services/newsfeed/package-lock.json
services/template/package-lock.json
services/transaction-statistics/config.js
services/transaction-statistics/package-lock.json
services/transaction-statistics/shared/buildTransactionStatistics.js
tests/package-lock.json

This PR resolves #1485 
Locally against Lisk Core running on v6.0.0-alpha.14

Update Lisk SDK to v6.0.0-alpha.14

---

services/export/jest.config.functional.js
services/export/jest.config.unit.js
services/export/shared/requestAll.js
services/export/tests/unit/shared/helpers/account.test.js
services/export/tests/unit/shared/helpers/csv.test.js
services/export/tests/unit/shared/helpers/file.test.js
services/export/tests/unit/shared/helpers/time.test.js
services/export/tests/unit/shared/helpers/transaction.test.js
services/export/tests/unit/shared/requestAll.test.js
services/newsfeed/jest.config.functional.js
services/newsfeed/jest.config.unit.js
services/newsfeed/shared/twitter.js
services/newsfeed/tests/functional/shared/twitter.test.js
services/newsfeed/tests/unit/shared/normalizers.test.js
services/newsfeed/tests/unit/shared/twitter.test.js
services/newsfeed/tests/unit/twitter.test.js

This PR resolves #1471
- Add the following unit tests to the newsfeed microservice
- services/newsfeed/shared/twitter.js
- services/export/shared/requestAll.js
- Add following functional tests to export microservice
- Add the following unit tests to the newsfeed microservice

Add unit tests for newsfeed microservice

---

services/blockchain-connector/Dockerfile

This PR resolves #1507 
- Remove apk dependency versions from Dockerfile
Locally: `make build`

Unable to build Docker images

---

services/blockchain-app-registry/shared/metadata.js
services/gateway/apis/http-version3/swagger/definitions/blockchainApps.json
tests/schemas/api_v3/blockchainAppsMetadataSchema.schema.js

Add isDefault to apps meta response

---

framework/package-lock.json
jenkins/mysql/docker-compose.yml
package-lock.json
services/blockchain-app-registry/package-lock.json
services/blockchain-connector/package-lock.json
services/blockchain-connector/package.json
services/blockchain-connector/shared/sdk/constants/eventTopics.js
services/blockchain-connector/shared/sdk/peerCache.js
services/blockchain-coordinator/package-lock.json
services/blockchain-indexer/package-lock.json
services/blockchain-indexer/package.json
services/export/package-lock.json
services/export/package.json
services/fee-estimator/package-lock.json
services/fee-estimator/package.json
services/gateway/apis/http-version3/swagger/parameters/transactions.json
services/gateway/package-lock.json
services/market/package-lock.json
services/newsfeed/package-lock.json
services/template/package-lock.json
services/transaction-statistics/package-lock.json
tests/package-lock.json

This PR resolves #1529 
Locally against Lisk Core branch `742-update-lisk-sdk-to-v6-0-0-alpha-16`

Update Lisk SDK to v6.0.0-alpha.16

---

services/blockchain-connector/Dockerfile
services/gateway/Dockerfile

This PR resolves #1542
Update the existing dockerfiles
By running existing test cases. No new testcases failed after adding the changes.

Update Dockerfile - #1542

---

services/blockchain-indexer/shared/dataService/business/blocks.js
tests/integration/api_v3/rpc/blocks.test.js
tests/schemas/api_v3/block.schema.js

This PR resolves #1545 
- Update integration test schema for blocks

numberOfEvents missing in new block event payload

---

services/blockchain-connector/config.js
services/blockchain-connector/package-lock.json
services/blockchain-connector/package.json
services/blockchain-connector/shared/sdk/client.js
services/blockchain-connector/shared/sdk/genesisBlock.js
services/blockchain-indexer/package-lock.json
services/blockchain-indexer/package.json
services/export/package-lock.json
services/export/package.json
services/fee-estimator/package-lock.json
services/fee-estimator/package.json

Update Lisk SDK to v6.0.0-alpha.18

---

framework/src/delay.js
services/blockchain-app-registry/shared/metadataIndex.js
services/blockchain-app-registry/shared/utils/downloadRepository.js
services/blockchain-app-registry/tests/constants/downloadRepository.js
services/blockchain-app-registry/tests/constants/metadataIndex.js
services/blockchain-app-registry/tests/functional/shared/metadataIndex.test.js
services/blockchain-app-registry/tests/unit/shared/utils/downloadRepository.test.js
services/blockchain-connector/shared/utils/delay.js
services/gateway/tests/unit/shared/waitForIt.test.js

This PR resolves #1552
- Functional tests are added for the following methods in services/blockchain-app-registry/shared/metadataIndex.js
- Unit tests are added for the following methods in services/blockchain-app-registry/shared/utils/downloadRepository.js

Add functional tests for app-registry

---

services/blockchain-connector/package-lock.json
services/blockchain-connector/package.json
services/blockchain-indexer/package-lock.json
services/blockchain-indexer/package.json
services/export/package-lock.json
services/export/package.json
services/fee-estimator/package-lock.json
services/fee-estimator/package.json

Update Lisk SDK to v6.0.0-alpha.22

---

services/blockchain-app-registry/shared/metadata.js

Incorrect total in response meta

---

services/blockchain-app-registry/shared/metadata.js
tests/integration/api_v3/http/blockchainAppsMetadata.test.js
tests/integration/api_v3/rpc/blockchainAppsMetadata.test.js

Blockchain application off-chain meta endpoint does not adhere to the limits

---

docs/api/version3.md
services/blockchain-indexer/config.js
services/blockchain-indexer/methods/dataService/controllers/token.js
services/blockchain-indexer/methods/dataService/modules/token.js
services/blockchain-indexer/shared/dataService/business/index.js
services/blockchain-indexer/shared/dataService/business/token.js
services/blockchain-indexer/shared/dataService/index.js
services/blockchain-indexer/shared/dataService/token/index.js
services/blockchain-indexer/shared/dataService/token/token.js
services/blockchain-indexer/shared/database/schema/accountBalances.js
services/blockchain-indexer/shared/indexer/accountBalanceIndex.js
services/blockchain-indexer/shared/indexer/accountIndex.js
services/blockchain-indexer/shared/indexer/blockchainIndex.js
services/blockchain-indexer/shared/indexer/genesisBlock.js
services/blockchain-indexer/tests/constants/events.js
services/blockchain-indexer/tests/functional/shared/indexer/acccountBalanceIndex.test.js
services/export/config.js
services/export/shared/csvExport.js
services/gateway/apis/http-version3/methods/modules/token/tokenAvailableIDs.js
services/gateway/sources/version3/tokenAvailableIDs.js
services/gateway/sources/version3/tokenTopBalances.js
services/gateway/tests/constants/generateDocs.js
services/transaction-statistics/config.js
services/transaction-statistics/shared/buildTransactionStatistics.js
tests/integration/api_v3/http/tokenAvailableIDs.test.js
tests/integration/api_v3/rpc/tokenAvailableIDs.test.js
tests/schemas/api_v3/tokenAvailableIDs.schema.js

Index balances by address and tokenID

---

docs/api/version3.md
services/blockchain-indexer/shared/dataService/business/validator/validatorInfo.js
services/blockchain-indexer/shared/database/schema/validators.js
services/blockchain-indexer/shared/indexer/transactionProcessor/legacy/registerKeys.js
services/blockchain-indexer/shared/indexer/transactionProcessor/pos/registerValidator.js
services/gateway/apis/http-version3/swagger/definitions/validators.json
tests/schemas/api_v3/validatorSchema.schema.js

This PR resolves #1605 
1. Started lisk-core and lisk-service
2. Ran stress tests for lisk-core (stress tests registers validators and keys)
3. Queried validators table in Mysql to check proofOfPossession

 Update proofOfPosession to proofOfPossession

---

services/blockchain-app-registry/package-lock.json
services/blockchain-app-registry/package.json
services/blockchain-connector/package-lock.json
services/blockchain-connector/package.json
services/blockchain-coordinator/package-lock.json
services/blockchain-coordinator/package.json
services/blockchain-indexer/package-lock.json
services/blockchain-indexer/package.json
services/export/package-lock.json
services/export/package.json
services/fee-estimator/package-lock.json
services/fee-estimator/package.json
services/gateway/package-lock.json
services/gateway/package.json
services/market/package-lock.json
services/market/package.json
services/template/package-lock.json
services/template/package.json
services/transaction-statistics/package-lock.json
services/transaction-statistics/package.json

This PR resolves #1639 
Run Lisk Service against a local Lisk Core node running on beta.1

Update Lisk SDK to v6.0.0-beta-1

---

services/blockchain-connector/Dockerfile
services/gateway/Dockerfile

This PR resolves #1662 
- Update Dockerfile(s) to use fuzzy versioning (major only) for APK package dependencies
- make build

Ease apk package pinning in Dockerfile

---

services/gateway/README.md
services/gateway/app.js
services/gateway/config.js

Make cors accept origin configurable

---

services/blockchain-app-registry/shared/metadata.js

Error querying metadata for supported tokens

---

services/market/config.js
services/market/shared/market/priceUpdater.js
services/market/shared/market/sources/exchangeratesapi.js

This PR resolves #1551 
- Make code generic/dynamic
Locally

Extend currency support for market prices

---

services/blockchain-indexer/shared/constants.js
services/blockchain-indexer/shared/dataService/business/transactions.js
services/blockchain-indexer/shared/dataService/transactions.js
services/blockchain-indexer/shared/indexer/blockchainIndex.js
services/blockchain-indexer/shared/indexer/transactionProcessor/0_moduleName/commandName1.js
services/blockchain-indexer/shared/indexer/transactionProcessor/0_moduleName/commandName2.js
services/blockchain-indexer/shared/indexer/transactionProcessor/auth/registerMultisignature.js
services/blockchain-indexer/shared/indexer/transactionProcessor/legacy/registerKeys.js
services/blockchain-indexer/shared/indexer/transactionProcessor/pos/changeCommission.js
services/blockchain-indexer/shared/indexer/transactionProcessor/pos/registerValidator.js
services/blockchain-indexer/shared/indexer/transactionProcessor/pos/reportMisbehavior.js
services/blockchain-indexer/shared/indexer/transactionProcessor/pos/stake.js
services/blockchain-indexer/shared/indexer/transactionProcessor/pos/updateGeneratorKey.js
services/blockchain-indexer/shared/indexer/transactionProcessor/token/transfer.js
services/blockchain-indexer/shared/indexer/transactionProcessor/token/transferCrossChain.js

Consider transaction execution status within the hooks

---

services/transaction-statistics/shared/buildTransactionStatistics.js

This PR resolves #1686 
Local against `devnet`
- pm2
- debugger
- docker

Fix transaction statistics

---

docs/antora/modules/ROOT/nav.adoc
docs/antora/modules/ROOT/pages/setup/docker.adoc

Update docker setup guide - Closes 1647

---

services/blockchain-app-registry/README.md
services/blockchain-app-registry/config.js
services/blockchain-connector/README.md
services/blockchain-connector/config.js
services/blockchain-coordinator/README.md
services/blockchain-coordinator/config.js
services/blockchain-indexer/README.md
services/blockchain-indexer/config.js
services/export/README.md
services/export/config.js
services/fee-estimator/README.md
services/gateway/README.md
services/gateway/config.js
services/market/README.md
services/market/config.js
services/transaction-statistics/README.md
services/transaction-statistics/config.js

Update microservice documentation 

---

docs/antora/modules/ROOT/nav.adoc
docs/antora/modules/ROOT/pages/configuration/docker.adoc
docs/antora/modules/ROOT/pages/index.adoc
docs/antora/modules/ROOT/pages/management/docker.adoc
docs/antora/modules/ROOT/pages/setup/source.adoc

Update docker commands in Lisk Service docs v0.7.0

---

framework/package-lock.json
package-lock.json
services/blockchain-app-registry/package-lock.json
services/blockchain-connector/package-lock.json
services/blockchain-connector/package.json
services/blockchain-coordinator/package-lock.json
services/blockchain-indexer/package-lock.json
services/blockchain-indexer/package.json
services/export/package-lock.json
services/fee-estimator/package-lock.json
services/fee-estimator/package.json
services/gateway/package-lock.json
services/market/package-lock.json
services/template/package-lock.json
services/transaction-statistics/package-lock.json
tests/package-lock.json

This PR resolves #1735 
Local against Lisk Core on branch [807-update-lisk-sdk-to-v6-0-0-beta-5](https://github.com/LiskHQ/lisk-core/tree/807-update-lisk-sdk-to-v6-0-0-beta-5)

Update SDK to v6.0.0-beta.5

---

docs/antora/modules/ROOT/nav.adoc
docs/antora/modules/ROOT/pages/management/source.adoc

This PR resolves #1705
The content was updated accordingly.

Update pm2 commands' page - Closes 1705

---

docs/antora/modules/ROOT/pages/configuration/index.adoc
docs/antora/modules/ROOT/pages/management/docker.adoc
docs/antora/modules/ROOT/pages/management/source.adoc
docs/antora/modules/ROOT/pages/setup/docker.adoc
docs/antora/modules/ROOT/pages/setup/source.adoc

Align code snippets

---

services/blockchain-coordinator/shared/scheduler.js
services/blockchain-coordinator/shared/sources/indexer.js
services/blockchain-indexer/methods/indexer/indexer.js
services/blockchain-indexer/shared/indexer/blockchainIndex.js

Paginate missed blocks queries

---

Makefile
services/blockchain-connector/package-lock.json
services/blockchain-connector/package.json
services/blockchain-connector/shared/sdk/interoperability.js
services/blockchain-indexer/package-lock.json
services/blockchain-indexer/package.json
services/export/package-lock.json
services/export/package.json
services/fee-estimator/package-lock.json
services/fee-estimator/package.json
tests/package-lock.json
tests/package.json

This PR resolves #1776  #1775
Local

Update Lisk SDK to v6.0.0-beta.6

---

docs/antora/modules/ROOT/pages/setup/source.adoc

Bump node version to 18 in setup guides in Lisk service docs

---

services/blockchain-connector/shared/sdk/endpoints.js
services/blockchain-indexer/shared/dataService/business/token/summary.js
services/blockchain-indexer/shared/dataService/business/transactionsEstimateFees.js

This PR resolves #1813 
Locally

`/token/summary` returns incorrect response

---

services/gateway/app.js
services/gateway/shared/moleculer-web/methods.js
services/gateway/shared/registerHttpApi.js

Gateway does not return response on upstream service error

---

services/blockchain-indexer/shared/indexer/transactionProcessor/nft/index.js
services/blockchain-indexer/shared/indexer/transactionProcessor/nft/transfer.js
services/blockchain-indexer/shared/indexer/transactionProcessor/nft/transferCrossChain.js

Implement transaction processor for NFT module

---

docs/antora/modules/ROOT/pages/index.adoc

Add Remark according to README - Closes 1838

---

docs/antora/modules/ROOT/pages/setup/docker.adoc
docs/antora/modules/ROOT/pages/setup/source.adoc

Closes https://github.com/LiskHQ/lisk-docs/issues/1279

Add HW requirements in Lisk service docs

---

services/blockchain-connector/shared/sdk/client.js
services/blockchain-connector/shared/sdk/constants/eventTopics.js
services/blockchain-coordinator/shared/scheduler.js
services/blockchain-indexer/shared/indexer/blockchainIndex.js

This PR resolves #1919 
Locally against testnet

Redis OOM errors

---

services/blockchain-indexer/shared/indexer/blockchainIndex.js

Error when handling deleted blocks

---

services/blockchain-indexer/shared/dataService/business/interoperability/constants.js

Resolve TODO

---

docker-compose.yml
docs/antora/modules/ROOT/pages/setup/source.adoc
jenkins/docker-compose.nightly.yml
jenkins/redis/docker-compose.yml

This PR resolves #1973 
Local + Mainnet

Upgrade Redis version

---

docs/api/websocket_subscribe_api.md
ecosystem.config.js
ecosystem.jenkins.config.js
services/blockchain-connector/shared/sdk/cache.js
services/blockchain-indexer/config.js
services/blockchain-indexer/shared/constants.js
services/blockchain-indexer/shared/indexer/genesisBlock.js

This PR resolves #1974 
Locally (Docker/PM2) + Server (PM2) deployment

Index valid generatorKeys from genesis assets

---

services/blockchain-app-registry/events/metadata.js
services/blockchain-connector/app.js
services/blockchain-connector/config.js
services/blockchain-connector/shared/geolocation.js
services/blockchain-connector/shared/sdk/blocksUtils.js
services/blockchain-connector/shared/sdk/client.js
services/blockchain-connector/shared/sdk/events.js
services/blockchain-connector/shared/utils/download.js
services/blockchain-coordinator/app.js
services/blockchain-indexer/app.js
services/blockchain-indexer/events/blockchain.js
services/blockchain-indexer/shared/dataService/blocks.js
services/blockchain-indexer/shared/indexer/blockchainIndex.js
services/blockchain-indexer/shared/indexer/transactionProcessor/0_moduleName/commandName1.js
services/blockchain-indexer/shared/indexer/transactionProcessor/0_moduleName/commandName2.js
services/export/jobs/purge.js
services/fee-estimator/shared/dynamicFees.js
services/fee-estimator/shared/utils/dynamicFees.js
services/gateway/app.js
services/gateway/shared/ready.js
services/market/jobs/binance.js
services/market/jobs/bittrex.js
services/market/jobs/exchangeratesapi.js
services/market/jobs/kraken.js
services/market/jobs/pricesUpdate.js
services/template/jobs/job.js
services/transaction-statistics/shared/buildTransactionStatistics.js

Connector creates too many ws connections with the node which stresses out the node

---

docs/redis_authentication.md

This PR resolves #1987 
Locally

Add authentication support for Redis (documentation)

---

services/blockchain-indexer/shared/indexer/utils/validator.js

Indexing failing due to zero self stake

---

docs/antora/modules/ROOT/pages/setup/source.adoc

Update Redis set up instructions in Lisk service docs

---

framework/yarn.lock
services/blockchain-app-registry/yarn.lock
services/blockchain-connector/package.json
services/blockchain-connector/yarn.lock
services/blockchain-coordinator/yarn.lock
services/blockchain-indexer/package.json
services/blockchain-indexer/shared/constants.js
services/blockchain-indexer/shared/dataService/pos/validators.js
services/blockchain-indexer/yarn.lock
services/export/yarn.lock
services/fee-estimator/package.json
services/fee-estimator/yarn.lock
services/gateway/yarn.lock
services/market/yarn.lock
services/template/yarn.lock
services/transaction-statistics/yarn.lock
tests/package.json
tests/yarn.lock
yarn.lock

… transactions
This PR resolves #1992 
Local

Validator rank/stake is not adjusted after a punishment

---

services/blockchain-connector/config.js
services/blockchain-connector/events/controller/blockchain.js
services/blockchain-connector/shared/sdk/client.js
services/blockchain-connector/shared/sdk/events.js
services/blockchain-connector/shared/sdk/interoperability.js
services/blockchain-connector/shared/sdk/pos.js
services/blockchain-connector/shared/sdk/token.js
services/blockchain-coordinator/shared/scheduler.js
services/blockchain-indexer/shared/indexer/genesisBlock.js

This PR resolves #2011 
Local + Server against both networks (`mainnet` and `testnet`)

Optimise implementation for indexing genesis accounts balance

---

services/blockchain-connector/shared/sdk/events.js

This PR resolves #2048 
Locally, against the mainnet with HTTP API enabled

Token summary not updated when using HTTP API
