services/core/jobs/peers.js
services/core/methods/controllers/peers.js
services/core/shared/core/compat/common/constants.js
services/core/shared/core/compat/sdk_v2/coreV1Mappings.js
services/core/shared/core/compat/sdk_v2/coreV3Mappings.js
services/core/shared/core/compat/sdk_v2/coreVersionCompatibility.js
services/core/shared/core/compat/sdk_v2/mappings.js
services/core/shared/core/compat/sdk_v3/mappings.js
services/core/shared/core/index.js
services/core/shared/core/peerCache.js
services/core/shared/core/peers.js
services/gateway/sources/mappings/peer.js
tests/integration_testnet/api/http/peers.test.js
tests/integration_testnet/schemas/peer.schema.js

Migrate peer cache to blockchain data store - Closes #135

---

services/core/config.js
services/core/jobs/dbCleanup.js
services/core/jobs/transactionStatistics.js
services/core/shared/core/purge.js
services/core/shared/pouchdb.js

This PR resolves #138 
Add jobs to clean up DB to reclaim space by removing old:
**NOTE:** Space reclamation is automatic as the `auto_compaction` is enabled on all the DBs. Refer to the PouchDB [documentation regarding auto-compaction](https://pouchdb.com/guides/compact-and-destroy.html#auto-compaction) for more information.
Local

Implement blockchain data storage data retention - Closes #138

---

services/core/events/blockchain.js
services/core/jobs/feeEstimates.js
services/core/methods/controllers/fees.js
services/core/shared/core/blocks.js
services/core/shared/core/dynamicFees.js
services/core/shared/core/index.js
services/gateway/shared/registerHttpApi.js
tests/integration/api/http/feeEstimate.test.js
tests/integration/api/http/networkSearch.test.js
tests/jest.config.integration.js
tests/schemas/feeEstimate.schema.js

Fix dynamic fees empty response - Closes #211

---

services/core/.npmrc
services/core/package-lock.json
services/core/package.json

Use default npmjs registry for service/core - Closes #122

---

services/core/shared/core/compat/sdk_v4/accounts.js

Remove multisignature properties for Non-Multisig accounts - Closes #280

---

services/gateway/apis/http-version1-compat/methods/voters.js
services/gateway/apis/http-version1-compat/methods/votes.js
services/gateway/apis/http-version1/methods/votesReceived.js
services/gateway/apis/http-version1/methods/votesSent.js
services/gateway/shared/paramValidator.js
services/gateway/shared/registerHttpApi.js
services/gateway/shared/registerRpcApi.js
tests/integration/api/http/votesReceived.test.js
tests/integration/api/http/votesSent.test.js
tests/integration/api/rpc/votesReceived.test.js
tests/integration/api/rpc/votesSent.test.js

Vote endpoints without a param causes wrong HTTP response - Closes #233

---

services/core/methods/controllers/delegates.js

Fix latest_registrations retrieval - Closes #315

---

services/core/config.js
services/core/methods/controllers/delegates.js
services/core/shared/core/compat/sdk_v4/blocks.js
services/core/shared/core/compat/sdk_v4/transactions.js
services/core/shared/core/compat/sdk_v4/voters.js

Fix non-indexed transaction calls - Closes # 316

---

services/core/shared/core/delegates.js
services/gateway/apis/http-version1/methods/delegates.js
services/gateway/sources/version1/delegates.js
tests/integration/api/http/delegates.test.js
tests/integration/api/rpc/delegates.test.js

Improve delegate filtering - Closes #329

---

Jenkinsfile.deployment
docker/Makefile.deployment.betanet5
docker/docker-compose.betanet5.yml
docker/lisk_service/docker-compose.core.yml
docker/lisk_service/env/network/betanet5.env

This PR changes the Jenkins job to run against betanet5 
Modified Jenkinsfile.deployment, added relevant betanet5 docker compose and env files
Tested on Jenkins
Also adds workaround for https://github.com/docker/for-linux/issues/264

Make Jenkins CI run against Betanet 5

---

services/core/shared/core/compat/common/constants.js
services/core/shared/core/compat/common/index.js
services/core/shared/core/compat/sdk_v5/blocks.js
services/core/shared/core/compat/sdk_v5/schema/blocks.js
services/core/shared/core/compat/sdk_v5/transactions.js
services/core/shared/core/compat/sdk_v5/voters.js
services/core/shared/indexdb/mysql.js

Improve block indexing - Closes #360

---

services/core/events/blockchain.js
services/core/methods/controllers/accounts.js
services/core/shared/core/compat/sdk_v4/delegates.js
services/core/shared/core/compat/sdk_v5/delegates.js
services/core/shared/core/delegates.js
services/core/shared/core/events.js

Fix vote weight calculation - Closes #381

---

services/core/benchmark/benchmark.js
services/core/benchmark/fileUtils.js
services/core/jobs/delegates.js
services/core/methods/controllers/transactions.js
services/core/methods/transactions.js
services/core/shared/core/compat/common/wsRequest.js
services/core/shared/core/compat/sdk_v2/index.js
services/core/shared/core/compat/sdk_v5/coreApi.js
services/core/shared/core/compat/sdk_v5/index.js
services/core/shared/core/compat/sdk_v5/postTransactions.js
services/core/shared/core/index.js
services/core/shared/core/transactions.js
services/gateway/apis/http-version2/methods/postTransactions.js
services/gateway/app.js
services/gateway/sources/version2/postTransactions.js

Enable transaction broadcast - Closes #259

---

services/core/shared/core/compat/sdk_v5/voters.js
services/core/shared/core/compat/sdk_v5/votes.js
services/gateway/apis/http-version2/methods/votesReceived.js
services/gateway/apis/http-version2/methods/votesSent.js
services/gateway/sources/version2/voters.js
services/gateway/sources/version2/votes.js
tests/integration/api_v2/http/votesReceived.test.js
tests/integration/api_v2/http/votesSent.test.js
tests/integration/api_v2/rpc/votesReceived.test.js
tests/integration/api_v2/rpc/votesSent.test.js

Make votes endpoint follow the specification - Closes #407 #408

---

Jenkinsfile
services/core/shared/core/compat/sdk_v5/accounts.js
services/core/shared/core/compat/sdk_v5/blocks.js
services/core/shared/core/compat/sdk_v5/transactions.js

Genesis block accounts indexing - Closes #421

---

services/core/shared/core/blocks.js
services/core/shared/core/compat/sdk_v5/accounts.js
services/core/shared/core/compat/sdk_v5/blocks.js
services/core/shared/core/compat/sdk_v5/transactions.js
services/core/shared/indexdb/mysql.js
services/gateway/sources/version2/mappings/account.js
tests/integration/api_v2/http/blocks.test.js
tests/integration/api_v2/http/transactions.test.js
tests/integration/api_v2/rpc/blocks.test.js
tests/integration/api_v2/rpc/transactions.test.js
tests/schemas/transaction.schema.js

Transaction/block filter support for half bounded ranges - Closes #435

---

services/core/shared/core/compat/sdk_v5/peers.js

Fix disconnected peers - Closes #488

---

services/core/shared/core/compat/sdk_v5/blocks.js
services/core/shared/indexdb/mysql.js
tests/integration/api_v2/http/accounts.test.js
tests/integration/api_v2/http/blocks.test.js
tests/integration/api_v2/http/delegates.test.js
tests/integration/api_v2/http/peers.test.js
tests/integration/api_v2/http/transactions.test.js
tests/integration/api_v2/rpc/accounts.test.js
tests/integration/api_v2/rpc/blocks.test.js
tests/integration/api_v2/rpc/delegates.test.js
tests/integration/api_v2/rpc/peers.test.js
tests/integration/api_v2/rpc/transactionStatistics.test.js
tests/integration/api_v2/rpc/transactions.test.js

Sorting by amount returns null values - Closes #499

---

services/market/config.js
services/market/jobs/updatePricesBittrex.js
services/market/package-lock.json
services/market/package.json
services/market/shared/market/index.js
services/market/shared/market/sources/bittrex.js
services/market/shared/market/sources/index.js

Add Bittrex data source - Closes #465

---

services/core/shared/core/compat/sdk_v5/coreApi.js

Update reclaim transaction warning - Closes #532

---

services/gateway/app.js

Add support for HTTP ETag - Closes #443

---

services/core/shared/core/compat/sdk_v5/accounts.js
services/gateway/sources/version2/mappings/account.js
services/market/shared/market/priceUpdater.js
services/market/tests/unit/pricesUpdater.test.js
tests/schemas/api_v2/account.schema.js

Fix delegate properties - Closes #550

---

services/core/shared/core/compat/sdk_v5/accounts.js

Fix lastForgedHeight retrieval - Closes #610

---

docker/lisk-service/env/gateway.env
services/gateway/config.js
services/gateway/shared/registerHttpApi.js

Add support for HTTP 'Cache-Control' - Closes #632

---

services/core/.dockerignore
services/core/.gitignore
services/core/config.js
services/core/package-lock.json
services/core/package.json
services/core/shared/arrayUtils.js
services/core/shared/core/compat/common/constants.js
services/core/shared/core/compat/common/wsRequest.js
services/core/shared/core/compat/sdk_v5/accounts.js
services/core/shared/core/compat/sdk_v5/blocks.js
services/core/shared/core/compat/sdk_v5/blocksUtils.js
services/core/shared/core/compat/sdk_v5/coreApi.js
services/core/shared/core/delegates.js
services/core/shared/core/peerCache.js
services/core/shared/knownAccounts.js

Update genesis block retrieval configuration - Closes #640

---

services/core/shared/core/compat/sdk_v5/dynamicFees.js

Fix fee estimator genesis height - Closes #653

---

services/core/shared/core/compat/sdk_v5/blocks.js

Use networkConstants cache for past blocks - Closes #643

---

Jenkinsfile
services/core/events/blockchain.js
services/core/events/ready.js
services/core/package-lock.json
services/core/package.json
services/core/ready.js
services/core/shared/core/compat/common/wsRequest.js
services/core/shared/core/compat/sdk_v2/index.js
services/core/shared/core/compat/sdk_v3/index.js
services/core/shared/core/compat/sdk_v4/blocks.js
services/core/shared/core/compat/sdk_v4/transactions.js
services/core/shared/core/compat/sdk_v5/blocks.js
services/core/shared/core/delegates.js
services/core/shared/core/events.js
services/core/shared/core/peerCache.js
services/core/shared/core/transactionStatistics.js
services/core/shared/signals.js

Update Signal listener - Closes # 648

---

docs/api/version2.md
services/core/config.js
services/core/shared/core/compat/sdk_v5/accounts.js
services/gateway/sources/version2/mappings/account.js

Fix delegate vote weight calculation - Closes #669

---

services/core/shared/core/compat/sdk_v5/accounts.js
services/core/shared/core/compat/sdk_v5/blocks.js
services/core/shared/core/delegates.js
services/core/shared/core/events.js
services/core/shared/core/transactions.js
services/core/shared/indexdb/mysql.js

Fix produced blocks and rewards calculation - Closes #676

---

docker/lisk-service/docker-compose.core.yml
docker/lisk-service/env/core.env
docker/redis/redis.volatile.conf
services/core/config.js
services/core/shared/core/compat/sdk_v5/accounts.js
services/core/shared/core/compat/sdk_v5/events.js
services/core/shared/core/events.js

Cache accounts - Closes #688

---

ecosystem.core3.config.js
ecosystem.jenkins.config.js
services/core/config.js
services/core/shared/core/compat/sdk_v5/blocks.js

Make genesis block indexing able to resume - Closes #719

---

services/core/shared/core/compat/sdk_v5/accounts.js

Fix unlocking objects for accounts - Closes #894

---

services/core/shared/core/compat/sdk_v5/pendingTransactions.js
services/core/shared/core/transactions.js
services/gateway/shared/paramValidator.js

Fix transactions query with includePending param - Closes #883

---

services/core/shared/core/delegates.js
services/gateway/apis/http-version2/swagger/parameters/common.json
services/gateway/apis/http-version2/swagger/parameters/transactions.json

Mitigate rank calculation issues (standby -> active) -Closes #731

---

services/core/shared/core/compat/sdk_v5/index.js
services/core/shared/core/delegates.js

Fix delegate sort comparator - Closes #935

---

services/core/shared/core/compat/sdk_v5/blockchainIndex.js
services/core/shared/core/transactionStatistics.js

This PR resolves #820 
```
2022-02-03T14:55:46.873 WARN [queue] indexAccountsQueue Job failed,Deadlock encountered when indexing block at height 17651205. Will retry later.
2022-02-03T14:55:46.873 WARN [queue] indexAccountsQueue Job failed,Error: Deadlock encountered when indexing block at height 17651205. Will retry later.
at Queue.indexBlocks ([/Users/sameer/Documents/Lisk/github/lisk-service/services/core/shared/core/compat/sdk_v5/blockchainIndex.js:245:10]())
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal[/process/task_queues.js:97:5]())
```
Local

Mitigate MySQL layer deadlock issue - Closes #820

---

services/core/shared/core/delegates.js

Delegates incorrectly identified as standby - Closes #984

---

ecosystem.core3.config.js
framework/src/mapper.js
services/core/methods/api_v2/controllers/network.js
services/core/shared/core/compat/common/httpRequest.js
services/core/shared/core/compat/sdk_v5/blockchainIndex.js
services/core/shared/core/compat/sdk_v5/voters.js
services/core/shared/core/delegates.js
services/core/shared/core/dynamicFees.js
services/core/shared/core/events.js
services/core/shared/downloadFile.js
services/core/shared/geolocation.js
services/core/tests/unit/jsonTools.test.js
services/export/app.js
services/gateway/shared/customMapper.js
services/gateway/shared/moleculer-io/index.js
services/gateway/shared/registerHttpApi.js
services/market/shared/market/sources/binance.js
services/market/shared/market/sources/bittrex.js
services/market/shared/market/sources/exchangeratesapi.js
services/market/shared/market/sources/kraken.js
services/newsfeed/methods/controllers/newsfeed.js
tests/helpers/node.js
tests/integration/api_v2/http/votesReceived.test.js
tests/integration/api_v2/rpc/delegates.test.js
tests/mockserver/mockserver_lisk.js

This PR resolves #987 
Local (script-based verification)

Incorrect delegate sorting - Closes #987

---

services/core/shared/core/compat/common/wsRequest.js

This PR resolves #1000 
Local (Restart Lisk Core node multiple times while Lisk Service keeps running)

Lisk Service failing to reconnect to Lisk Core (intermittent) - Closes #1000

---

services/core/shared/core/compat/sdk_v5/paramUtils.js
services/core/shared/indexdb/mysql.js
services/core/tests/unit/paramUtils.test.js
services/newsfeed/shared/indexdb/mysql.js

Fix normalizeRangeParam method - Closes #1056

---

services/gateway/package.json
services/market/package-lock.json
services/market/tests/functional/market.prices.test.js
services/newsfeed/package-lock.json
services/newsfeed/tests/functional/newsfeed.test.js
services/newsfeed/tests/unit/normalizers.test.js

Update broken tests - Closes #1034

---

services/blockchain-connector/jobs/peers.js
services/gateway/apis/http-version3/methods/peers.js
services/gateway/sources/version3/mappings/peer.js
services/gateway/sources/version3/peers.js
tests/integration/api_v3/http/peers.test.js
tests/integration/api_v3/rpc/peers.test.js
tests/schemas/api_v3/peer.schema.js

Add endpoint to fetch peers - Closes #1092

---

services/gateway/apis/http-version3/methods/networkStatistics.js
services/gateway/sources/version3/networkStatistics.js
tests/integration/api_v3/http/networkStatistics.test.js
tests/integration/api_v3/rpc/networkStatistics.test.js
tests/schemas/api_v3/networkStatistics.schema.js

Add endpoint to fetch network statistics - Closes #1094

---

jenkins/Jenkinsfile.nightly
services/gateway/apis/http-version3/methods/transactionsStatistics.js
services/gateway/sources/version3/mappings/transactionsStatistics.js
services/gateway/sources/version3/transactionsStatistics.js
services/transaction-statistics/methods/controllers/transactions.js
services/transaction-statistics/methods/transactions.js
services/transaction-statistics/shared/transactionStatistics.js
services/transaction-statistics/shared/utils/requestAll.js
tests/integration/api_v3/http/transactionStatistics.test.js
tests/integration/api_v3/rpc/transactionStatistics.test.js
tests/schemas/api_v3/transactionStatistics.schema.js

Update endpoint to fetch transaction statistics - Closes #1091

---

services/blockchain-indexer/events/blockchain.js
services/blockchain-indexer/shared/dataService/business/generators.js
services/gateway/apis/http-version3/methods/generators.js
services/gateway/app.js
services/gateway/sources/version3/generators.js
services/gateway/sources/version3/mappings/generators.js
tests/integration/api_v3/http/generators.test.js
tests/integration/api_v3/rpc/generators.test.js
tests/schemas/api_v3/generatorSchema.schema.js
tests/schemas/api_v3/regex.js

Add endpoint to fetch generators - Closes #1096

---

services/blockchain-connector/config.js
services/blockchain-indexer/config.js
services/blockchain-indexer/jobs/dataService/blockchainAppsStats.js
services/blockchain-indexer/methods/dataService/controllers/blockchainApps.js
services/blockchain-indexer/shared/dataService/business/index.js
services/blockchain-indexer/shared/dataService/business/interoperability/blockchainAppsStats.js
services/blockchain-indexer/shared/dataService/business/interoperability/index.js
services/blockchain-indexer/shared/dataService/index.js
services/blockchain-indexer/shared/dataService/interoperability/blockchainAppsStats.js
services/blockchain-indexer/shared/dataService/interoperability/index.js

Compute blockchain app stats - Closes #1113

---

services/blockchain-indexer/config.js
services/blockchain-indexer/methods/dataService/blockchainApps.js
services/blockchain-indexer/methods/dataService/controllers/blockchainApps.js
services/blockchain-indexer/shared/dataService/business/interoperability/blockchainApps.js
services/blockchain-indexer/shared/database/schema/blockchainApps.js
services/blockchain-indexer/shared/indexer/transactionProcessor/interoperability/ccuMainchain.js
services/blockchain-indexer/shared/indexer/transactionProcessor/interoperability/ccuSidechain.js
services/blockchain-indexer/shared/indexer/transactionProcessor/interoperability/registerMainchain.js
services/blockchain-indexer/shared/indexer/transactionProcessor/interoperability/registerSidechain.js
services/gateway/apis/http-version3/methods/blockchainApps.js
services/gateway/shared/regex.js
services/gateway/sources/version3/blockchainAppsSchema.js
services/gateway/sources/version3/mappings/blockchainApp.js
tests/integration/api_v3/http/blockchainApps.test.js
tests/integration/api_v3/rpc/blockchainApps.test.js
tests/schemas/api_v3/blockchainAppsSchema.schema.js

Extend blockchain apps information - Closes #1181

---

jenkins/mariadb/docker-compose.yml
jenkins/mariadb/mysql-healthcheck.sh
services/blockchain-indexer/methods/dataService/controllers/tokens.js
services/blockchain-indexer/methods/dataService/tokens.js
services/blockchain-indexer/shared/dataService/business/index.js
services/blockchain-indexer/shared/dataService/business/tokens.js
services/blockchain-indexer/shared/dataService/index.js
services/blockchain-indexer/shared/dataService/token/index.js
services/blockchain-indexer/shared/utils/regex.js
services/blockchain-indexer/shared/utils/request.js
services/gateway/apis/http-version3/methods/supportedTokens.js
services/gateway/apis/http-version3/swagger/definitions/tokens.json
services/gateway/sources/version3/newsfeed.js
services/gateway/sources/version3/supportedTokens.js
services/newsfeed/shared/newsfeed.js
tests/integration/api_v3/http/supportedTokens.test.js
tests/integration/api_v3/rpc/supportedTokens.test.js
tests/schemas/api_v3/newsfeed.schema.js
tests/schemas/api_v3/tokens.schema.js

Add endpoint to fetch supported tokens - Closes #1217 #1226

---

jenkins/Jenkinsfile.nightly

This PR resolves #1329
The Jenkinsfile of lisk-service-nightly has been modified.
After merging to the development branch, if the lisk-service-nightly task fails, an e-mail will be sent to service@lightcurve.io

Notify after Jenkins lisk-service-nightly job fails

---

services/blockchain-indexer/package-lock.json
services/blockchain-indexer/package.json
services/blockchain-indexer/shared/constants.js
services/blockchain-indexer/shared/indexer/blockchainIndex.js
services/blockchain-indexer/shared/indexer/indexStatus.js
services/blockchain-indexer/shared/indexer/validatorIndex.js
services/blockchain-indexer/shared/utils/validatorUtils.js
services/gateway/apis/http-version3/swagger/definitions/events.json

Implement reward sharing

---

services/blockchain-connector/shared/sdk/dynamicReward.js

Fix `getDefaultRewardAtHeight` method in connector

---

services/blockchain-connector/shared/sdk/network.js
services/blockchain-indexer/shared/constants.js
services/blockchain-indexer/shared/dataService/business/events.js
services/blockchain-indexer/shared/dataService/business/index.js
services/blockchain-indexer/shared/dataService/index.js
services/blockchain-indexer/shared/database/schema/eventTopics.js
services/blockchain-indexer/shared/database/schema/events.js
services/blockchain-indexer/shared/indexer/blockchainIndex.js
services/blockchain-indexer/shared/utils/eventsUtils.js

Update totalLocked on block delete

---

services/blockchain-connector/methods/interoperability.js
services/blockchain-connector/shared/sdk/index.js
services/blockchain-connector/shared/sdk/interoperability.js
services/blockchain-connector/shared/sdk/pos.js
services/blockchain-connector/shared/utils/regex.js
services/blockchain-indexer/shared/dataService/business/index.js
services/blockchain-indexer/shared/dataService/business/interoperability/index.js
services/blockchain-indexer/shared/dataService/business/interoperability/mainchain.js
services/blockchain-indexer/shared/dataService/index.js
services/blockchain-indexer/shared/dataService/interoperability/mainchain.js
services/blockchain-indexer/shared/indexer/transactionProcessor/interoperability/registerMainchain.js
services/blockchain-indexer/shared/indexer/transactionProcessor/interoperability/registerSidechain.js
services/blockchain-indexer/shared/indexer/transactionProcessor/interoperability/submitSidechainCrossChainUpdate.js
services/blockchain-indexer/shared/indexer/transactionProcessor/interoperability/terminateSidechainForLiveness.js

Unable to index the registerMainchain transaction

---

services/blockchain-connector/Dockerfile
services/gateway/Dockerfile

This PR resolves #1580 
- make build
- Run against Lisk Core v4.0.0-alpha.19

Fix apk package pinning on Dockerfile

---

services/blockchain-connector/methods/transactions.js
services/blockchain-connector/shared/sdk/transactions.js
services/blockchain-indexer/methods/dataService/transactions.js
services/blockchain-indexer/shared/dataService/business/transactionsDryRun.js
services/gateway/apis/http-version3/methods/transactionsDryRun.js
services/gateway/apis/http-version3/swagger/definitions/transactions.json
services/gateway/sources/version3/transactionsDryRun.js
tests/integration/api_v3/http/transactionsDryRun.test.js
tests/integration/api_v3/rpc/transactionsDryRun.test.js
tests/schemas/api_v3/transactionsDryRun.schema.js

Add skipDecode support for transaction dryrun endpoint

---

services/blockchain-indexer/shared/indexer/transactionProcessor/interoperability/submitSidechainCrossChainUpdate.js

This PR resolves #1582
1. Ran a mainchain and 2 sidechains following this [documentation](https://github.com/LiskHQ/lisk-sdk/blob/development/examples/interop/README.md).
2. Ran lisk-service with fresh cleaned db against mainchain node.
3. Submitted a transfer transaction from mainchain to sidechain.
4. After a while queried http://localhost:9901/api/v3/blockchain/apps.
5. Without the changes address was "" but with the PR changes address was appearing correctly.

`address` unavailable in `/blockchain/apps` endpoint response

---

services/blockchain-app-registry/shared/database/schema/token_metadata.js
services/blockchain-app-registry/shared/metadata.js
services/blockchain-app-registry/shared/metadataIndex.js
services/blockchain-app-registry/shared/utils/downloadRepository.js
services/blockchain-app-registry/tests/functional/shared/metadataIndex.test.js
services/blockchain-app-registry/tests/unit/shared/metadataIndex.test.js
services/blockchain-app-registry/tests/unit/shared/utils/downloadRepository.test.js
services/transaction-statistics/shared/buildTransactionStatistics.js
services/transaction-statistics/shared/utils/constants.js

This PR resolves #1473
- Add unit test coverage forblockchain-app-registry/shared/metadataIndex.js

Remove globalTokenID logic from transaction-statistics

---

services/blockchain-indexer/shared/constants.js
services/blockchain-indexer/shared/dataService/business/pendingTransactions.js
services/blockchain-indexer/shared/dataService/pos/validators.js
services/blockchain-indexer/tests/unit/shared/dataservice/business/pendingTransactions.test.js

This PR resolves #1712 #1713 
Local
- docker
- debugger

Unable to query pending transactions by address

---

docs/antora/modules/ROOT/pages/setup/docker.adoc

Corrects a link to the older(v3) to (v4)npm setup guide.
The link now points to npm setup v4 of lisk-core.

Update npm setup guide reference

---

services/transaction-statistics/shared/buildTransactionStatistics.js

Transaction statistics crashes

---

services/blockchain-connector/shared/sdk/client.js
services/blockchain-connector/shared/sdk/events.js

Connector crashes on request timeouts

---

services/blockchain-indexer/shared/dataService/business/transactionsEstimateFees.js
services/blockchain-indexer/shared/regex.js
services/blockchain-indexer/shared/utils/parser.js
services/blockchain-indexer/tests/constants/metadata.js
services/blockchain-indexer/tests/constants/schemas.js
services/blockchain-indexer/tests/unit/shared/constants.test.js
services/blockchain-indexer/tests/unit/shared/dataservice/business/transactionEstimateFees.test.js
services/export/shared/helpers/file.js

This PR resolves #1824 
- API timeout when supplied with incorrect token ID for cross chain transfers. (Fixed by https://github.com/LiskHQ/lisk-service/pull/1818)
- API Timeout if recipient address is new and not initailized (Fixed by https://github.com/LiskHQ/lisk-service/pull/1818)
Local

Missing validation for estimate-fees API

---

docs/api/version3.md
services/blockchain-indexer/shared/dataService/business/interoperability/blockchainApps.js
services/blockchain-indexer/tests/unit/shared/constants/blockchainApps.js
services/blockchain-indexer/tests/unit/shared/dataservice/business/interoperability/blockchainApps.test.js
services/gateway/apis/http-version3/swagger/definitions/blockchainApps.json
services/gateway/sources/version3/mappings/blockchainApp.js
tests/schemas/api_v3/blockchainApps.schema.js

Extend blockchain apps endpoint response

---

framework/yarn.lock
services/blockchain-app-registry/yarn.lock
services/blockchain-connector/package.json
services/blockchain-connector/yarn.lock
services/blockchain-coordinator/yarn.lock
services/blockchain-indexer/yarn.lock
services/export/yarn.lock
services/fee-estimator/yarn.lock
services/gateway/yarn.lock
services/market/yarn.lock
services/template/yarn.lock
services/transaction-statistics/yarn.lock
tests/yarn.lock
yarn.lock

This PR resolves #1852
- Modify Makefile: replace `docker buildx build` with `docker buildx build --no-cache`
- Run `make build`

docker build fails because of missing node-gyp package

---

services/gateway/apis/http-version3/methods/fees.js
services/gateway/tests/constants/generateDocs.js

503 response not present in swagger for fees endpoint

---

services/blockchain-connector/tests/unit/delay.test.js
services/blockchain-connector/tests/unit/waitForIt.test.js
services/blockchain-indexer/shared/dataService/business/events.js
services/blockchain-indexer/tests/unit/shared/constants/events.js
services/blockchain-indexer/tests/unit/shared/dataservice/business/events.test.js
services/gateway/tests/unit/shared/waitForIt.test.js

Querying events by senderAddress errors

---

services/blockchain-connector/shared/sdk/client.js

This PR resolves #1920 
Locally
- Added: `if (Math.ceil(Math.random() * 10) % 2 === 0) throw new Error('Test API client fix');` within `instantiateClient` immediately after the IPC/WS API client instantiation logic and run against Lisk Core

Automatic API client re-instantiation fails

---

services/blockchain-indexer/methods/dataService/transactions.js
services/blockchain-indexer/shared/dataService/business/pendingTransactions.js
services/blockchain-indexer/shared/database/schema/transactions.js
services/blockchain-indexer/tests/unit/shared/constants/pendingTransactions.js
services/blockchain-indexer/tests/unit/shared/dataservice/business/pendingTransactions.test.js
services/blockchain-indexer/tests/unit/shared/dataservice/business/transactionEstimateFees.test.js
services/gateway/apis/http-version3/methods/transactions.js
services/gateway/apis/http-version3/swagger/parameters/transactions.json
services/gateway/sources/version3/transactions.js
services/gateway/tests/constants/generateDocs.js
tests/integration/api_v3/constants/invalidInputs.js
tests/integration/api_v3/http/transactions.test.js
tests/integration/api_v3/rpc/transactions.test.js

Add receivingChainID request param support to transactions endpoint

---

services/blockchain-connector/shared/sdk/cache.js
services/blockchain-indexer/shared/dataService/business/transactions.js
services/blockchain-indexer/shared/indexer/blockchainIndex.js
services/blockchain-indexer/shared/messageProcessor.js
services/blockchain-indexer/tests/unit/shared/dataservice/business/transactions.test.js

Empty data in delete transactions event payload

---

docker/nats-server.conf
ecosystem.config.js
ecosystem.jenkins.config.js
services/blockchain-connector/shared/sdk/client.js
services/blockchain-connector/shared/sdk/events.js
services/blockchain-connector/shared/sdk/index.js
services/blockchain-indexer/jobs/dataService/validators.js
services/blockchain-indexer/shared/indexer/blockchainIndex.js
services/blockchain-indexer/shared/indexer/genesisBlock.js

This PR resolves #1962 
- Follow "Steps to reproduce" from #1962

Fix mainnet genesis block indexing

---

services/blockchain-indexer/shared/dataService/business/pendingTransactions.js
services/blockchain-indexer/tests/unit/shared/dataservice/business/pendingTransactions.test.js

Pending Transactions appear in transactions?blockID queries

---

services/blockchain-indexer/shared/indexer/accountBalanceIndex.js
services/blockchain-indexer/shared/indexer/genesisBlock.js

This PR resolves #2018
Locally

Top balances endpoint does not consider locked amounts

---

services/blockchain-indexer/shared/dataService/business/transactionsEstimateFees.js

This PR resolves #2022
Locally/ already patched on prod

Can't send transactions leaving the account with less than 0.05 LSK
